name: Deploy develop

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-east-2
  CV_API_URL: ${{ secrets.DEVELOP_CV_API_URL }}

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy develop
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEVELOP_AWS_ACCOUNT_ID }}:role/CICD-Role
          role-session-name: ci-cd-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build the page
        run: npm run build
